cozy/cozy.github.io

docs/install/manual.md
I read quickly the doc and spotted some typos.
=> fixed some typos on the installation manual

README.md
@clochix ; this small PR just to avoid some pain to future contributors to these docs ;)
=> Feat.readme mkdocs

src/dev/app.md, src/dev/index.md, src/dev/intro.md, src/dev/konnector.md, src/index.md, src/index_fr.md, src/install/manual.md, src/sync/index.md
according to the oxford dictionary
https://en.oxforddictionaries.com/punctuation/bullet-points
=> remove semicolons on bullet points

mkdocs.yml, src/dev/cordova.md, src/dev/index.md
It refers to some external documentation as the stack is non obvious:
1. cordova
1. java
1. android sdk
1. xcode
etc.
=> add cordova documentation

src/dev/cordova.md
J'ai ajouté quelques infos pour aider le développeur tiers à connecter son application mobile à la stack.
=> add cozy information

docs/fr/index_fr/index.html
Note: the link for IRC is wrongly set to forum on line 198
=> translating 3 strings

.gitignore, src/dev/konnector.md
En relisant la documentation de création d'un konnector, je profite d'en faire une relecture :
- 4046e8f change konnector doc sample commands
- d6efd1e chore: add .venv as gitignore
=> Review konnector documentation

src/dev/konnector.md
As I still work on the konnector, I will find more review to make, so, please, don't merge this PR too soon, even if you approve it.
=> review konnector docs

src/extra.js
Prevents [RSI] by allowing to use "/" to go directly to the search bar.
"Look ma, no mouse!"
[RSI]: https://en.wikipedia.org/wiki/Repetitive_strain_injury
=> feat: add keyboard shortcut to search with slash

.gitignore, src/dev/konnector.md
Enhance the how-to develop a connector documentation to fix the first point of https://github.com/konnectors/libs/issues/237
=> feat: enhance how-to documentation for konnector

OUTSIDE_DOCS
This will add the readme of cozy-app-publish after [this PR is merged](https://github.com/cozy/cozy-app-publish/pull/35).
=> Added cozy-app-publish docs

mkdocs.yml, src/dev/git-flow.md
This PR adds a guide explaining how we manage releases and patches in our applications and konnectors.
=> Add Git Flow

src/dev/git-flow.md
Two fixes I believe. Sorry if I made mistakes :)
If the doc has been modified by another pull request feel free to reject mine
=> Two small fixes.

src/dev/git-flow.md
This PR tries to make the Git Flow documentation more explicit.
=> Improve Git Flow documentation

src/dev/intro.md
=> fix: English tweaks

src/howTos/dev/services.md
How-to develop a cozy service from an app and run it on a local stack.
=> Add services how-to

src/tutorials/selfhost-debian.md
Clean reference to Ubuntu & nightly
Use GPG keyring package
=> Remove unsupported things

src/tutorials/selfhost-debian.md
No more onboarding standalone application, managed directly in stack
=> Remove onboarding

src/tutorials/app.md
=> Fix broken links

README.md
Update readme with new command use for fetching.
=> fix: Update README with new install commands

src/tutorials/konnector.md
As a response to https://forum.cozy.io/t/passing-secret-variables-to-connector/6597
=> doc: add documentation about COZY_PARAMETERS

requirements.txt
see https://nvd.nist.gov/vuln/detail/CVE-2018-18074 for more details.
=> core: Request 2.19.1 is vulnerable

README.md
- no need to install manually mkdocs since it is in requirements.txt
- add comment on virtualenv
- add comment on manual build
=> feat: Improve README

src/howTos/dev/services.md, src/tutorials/konnector/how-does-it-work.md, src/tutorials/konnector/save-data.md
- Fix broken links
- Add more links related to manifests and permissions
=> fix: links

src/tutorials/konnector/index.md, src/tutorials/konnector/oauth.md
Here is a documentation on how to develop an OAuth connector and also how to deploy it.
=> feat: add oauth connector development doc

src/tutorials/konnector/cozy-browser.md, src/tutorials/konnector/index.md
This is the documentation on how to use Cozy Browser in connectors (jsdom, zombiejs)
=> doc: add cozy browser for connector

src/howTos/dev/services.md
=> docs: Update link to Bank's service

src/howTos/dev/services.md
Let's initiate a CozyClient instance from a service
=> docs: CozyClient in a service

src/tutorials/app.md
This command is useful to avoid docker
=> docs: Add command to develop with local stack

mkdocs.yml, mkdocs.yml.tpl, requirements.txt
- Allow to use spacing indent of 2 for lists, similar to GitHub
=> feat: Use mdx-truly-sane-lists to fix problems with lists

src/howTos/dev/services.md, src/tutorials/data/advanced.md
* Inform that node-fetch should be use when developing services
* Update doc for partial indexes
=> Update service and partial index doc

src/howTos/dev/services.md
See https://github.com/cozy/create-cozy-app/pull/1373
=> docs: Precisions about the build

.gitignore, src/projects/index.md
Correction of the path to access the projects
=> Home and application page

OUTSIDE_DOCS
=> Add home docs

src/tutorials/data/pouchdb.md
Add an example taken from banks on how to automatically fire warm up queries.
=> docs: Document the warm up query options

src/tutorials/selfhost-debian.md
- separate config file lines from commands
- fix some wordings & typo
=> Improve selfhosting tutorial readability

mkdocs.yml.tpl, requirements.txt
We can have emoji in our md documentation. Let's support them.
https://docs.cozy.io/en/cozy-stack/jobs/#at-syntax
=> Feat: Support emoji

src/howTos/dev/run-connectors-on-local-cozy-stack.md
In order to have the right exit code and errors
=> docs: Update run-connectors-on-local-cozy-stack.md

src/howTos/dev/cordova.md
Hi, appEditor property doesnt seems to exists anymore https://github.com/cozy/cozy-bar/blob/master/src/index.jsx#L136
=> remove property appEditor

src/tutorials/selfhosting/selfhost-ubuntu-sources-en.md, src/tutorials/selfhosting/selfhost-ubuntu-sources-fr.md
Following a bad experience at installing cozy-stack when following the compilation documentation, this PR updates the doc to fix it in accordance with some recent changes in cozy stack and to make it more clear and easier.
=> docs: Fix selfhosting doc for recent stack version

src/howTos/dev/services.md
To be more precise about the debounce
=> docs: Update services.md

src/tutorials/selfhosting/administration/office.md, src/tutorials/selfhosting/finalize/create_instance.md, src/tutorials/selfhosting/finalize/nginx.md, src/tutorials/selfhosting/requirements/couchdb.md, src/tutorials/selfhosting/requirements/nodejs.md
Improve selfhosting documentation from first feedbacks
=> Improve selfhosting documentation from first feedbacks

src/tutorials/selfhosting/administration/office.md, src/tutorials/selfhosting/administration/upgrade.md, src/tutorials/selfhosting/finalize/create_instance.md, src/tutorials/selfhosting/index.md, src/tutorials/selfhosting/install/package.md, src/tutorials/selfhosting/install/sources.md, src/tutorials/selfhosting/requirements/couchdb-pkg.md, src/tutorials/selfhosting/requirements/couchdb-snap.md, src/tutorials/selfhosting/requirements/couchdb.md, src/tutorials/selfhosting/requirements/nodejs.md
Update selfhosting documentation after another feedback
=> docs: Improve selfhosting documentation

mkdocs.yml.tpl, src/tutorials/selfhosting/docker/index.md, src/tutorials/selfhosting/index.md
This PR adds documentation on how to self host using docker compose and docker images
=> Add docker compose selfhosting documentation

src/tutorials/CliSK/1 - Installation/1.2 - Development environnement setup.md, src/tutorials/CliSK/5 - Best practices/5.2 - Testing.md
Remove old "CliSK" directory form arbo
=> Remove useless CliSK directory
