cozy/cozy.github.io

src/install/manual.md
The command `systemctl enable couchdb.service`" failed with this message :
> The unit files have no [Install] section. They are not meant to be enabled
> using systemctl.
> Possible reasons for having this kind of units are:
> 1) A unit may be statically enabled by being symlinked from another unit's
>    .wants/ or .requires/ directory.
> 2) A unit's purpose may be to act as a helper for some other unit which has
>    a requirement dependency on it.
> 3) A unit may be started when needed via activation (socket, path, timer,
>    D-Bus, udev, scripted systemctl call, ...).
=> Fix Couchdb service script enabling

src/install/debian.md
Thanks to @Technowix, I notice aptly/apt sign the overall repository with the same GPG key instead to sign only a subpart. https://social.imirhil.fr/@aeris/421102
This fix move nightly repositories to a separated repository to segregate "weak" (online & passwordless) CI/nightly GPG key from the "strong" (offline & password protected) release one.
=> Change nightly repository URL to protect GPG key

.gitignore, .travis.yml, build.sh, deploy.sh, fetch.sh, mkdocs.yml, requirements.txt
Include docs from other repositories in a reference tab.
* `./fetch.sh` clones other repositories in /tmp and adds symbolic
links into `src`
* `cozy-client-js`
* `cozy-konnector-libs`
=> feat: include other docs

OUTSIDE_DOCS, add_outside_docs.py, fetch.sh, mkdocs.yml, requirements.txt
The idea is that it is the outside doc that best knows its table of contents
so it should be configured there.
Here we use a special `toc.yml` file from the outside documentation and include
it in the References directly. I added a toc file in `cozy-konnector-libs` as an
example : https://github.com/cozy/cozy-konnector-libs/blob/master/packages/cozy-konnector-libs/docs/toc.yml
Also, `fetch.sh` now reads from a file for the configuration of outside documentation.
It decouples code from config.
=> feat: auto table of contents

src/install/debian.md
Doc changes for ACME 0.20+
New third parties repositories are mandatory
=> 3rd-party repositories for ACME

add_external_docs.py, cozy-theme/toc.html, mkdocs.yml
To facilitate the edition of the documentation (in order to have the most
up-to-date documentation), a link is added in the sidebar to edit the file
on GitHub.
To support external documentation, a small Javascript snippet detects if the
current page is for an external doc and changes the edit link to point to
the right repository.
Fix #56.
=> feat: show edit links

add_external_docs.py, cozy-theme/toc.html, mkdocs.yml
This re-adds the functionality of e3a1e21 but only adds the links if we are on the english documentation.
The if line : https://github.com/cozy/cozy.github.io/pull/68/files#diff-d21f7a25bd788adc4c95d96566091cc7R12
This is not optimal as French readers will be our first audience. But this is the only possible way for now as it is harder to edit pot files. IMHO, we should find a better way to do i18n. I wonder if removing msgmerge and simply writing markdown files for french documentation would be OK ? This way we could also point the edit links to the French documentation.
=> feat: add edit links on english documentation

add_external_docs.py, cozy-theme/nav.html
Since some markdown files in external docs were not present in the
pages (because they are not in any table of contents), they were not
built by mkdocs and this would cause 404.
In this PR, files that are not present in pages but are present on the
filesystem are automatically added to a `hidden` section in pages.
This `hidden` section is not displayed in the nav (this is
by filtering directly in the template).
=> fix: add all md files to pages

README.md, build.sh, cozy-theme/nav.html, index.html, mkdocs.yml, requirements.txt
As for now the documentation will only host technical papers, so it will
be english only.
Remove everything that was used to translate it into other languages.
=> Remove l18n

src/install/debian.md
The file name and the `EOF` instruction may be confusing
=> replace file content by a command creating the file

README.md
Specify how to install requirements.text and which Python version to use, before executing `add_external_docs.py`
=> Add Python requirements installation

OUTSIDE_DOCS
Cozy-UI was missing from References.
=> feat: Add Cozy-UI to the nav

src/tutorials/app.md
There was no explanation that `cozy-scripts start` starts a stack/couchdb.
=> docs: Explain what cozy-scripts start does

src/extra.js
External READMEs edit links were not always working, now they do work
=> fix: External edit links work

OUTSIDE_DOCS, mkdocs.yml
Introduce an "Applications" part, containing only cozy banks for now.
Also use the tabs layout from mkdocs-material (see https://squidfunk.github.io/mkdocs-material/getting-started/#tabs):
=> Add cozy-banks documentation

mkdocs.yml
Par défaut on tombe sur le README des doctypes, et une très longue liste de doctype. Il me semble plus pertinent de tomber sur quelque chose de plus actif et plus court, j'ai donc inversé l'ordre.
=> Change order of the links inside "libraries"

src/tutorials/selfhost-debian.md
Hi,
Sysctl value is set temporary but not save in sysctl conf file, add command to save it on 99-cozy.conf.
In case of instance is rebooted, users can be panic to see his cozy broken :/.
=> doc: Set sysctl param permanent

OUTSIDE_DOCS
Add at least cozy-coclyco to the main entry. 
Next : better integration with the self hosted page?
`cozy-coclyco` is designed to create Cozy instances, manage nginx vhost and Let's encrypt certificate issuance.
=> feat: Add cozy-coclyco to the documentation

requirements.txt
Uses a deprecated export from setuptools that causes an
error on the CI
=> feat: Update MarkupSafe

mkdocs.yml.tpl
Include the "service" doc in our How-to section
=> docs: Add Develop a service to the HowTo Section

mkdocs.yml
Words like time_interval are could not be found in the search engine until now.
=> feat: handle words with _ in the search engine

src/tutorials/konnector/index.md
Currently it's hard to find the informations when you're looking at the konnector tutorial. It's not the ideal fix, but it's better than nothing
=> docs: Added a link to env vars

src/howTos/dev/services.md
It was mentioned in the next section, but it was easy to miss it. It is more explicit now.
=> docs: Add section about env vars

src/tutorials/data/queries.md
Redirect to the correct section in advanced concepts
=> docs: Fix broken link

mkdocs.yml.tpl, requirements.txt, src/references/tech-intro.md
- Do not exclude cozy-stack/docs/archives because they are referenced from other cozy-stack documentations
- Fix broken link to konnector tutorial
=> Fix broken links

src/tutorials/app.md
Since CCA's apps are using HMR by default, let's disable 
CSP by default even with docker.
=> docs: Update CSP for docker run

src/tutorials/konnector/index.md
We have a page "going further" with useful informations
but there is not link to go there. Let's at least and this 
link.
=> doc: Add link to Going Further

src/tutorials/selfhosting/selfhost-ubuntu-sources-en.md, src/tutorials/selfhosting/selfhost-ubuntu-sources-fr.md
See cmd/config.go. The environment variable it looks for is COZY_ADMIN_PASSPHRASE, not COZY_ADMIN_PASSWORD.
=> docs: Fix env variable name for config passwd

src/tutorials/konnector/going-further.md
Konnectors errors should be listed in Konnector-Libs. 
Also, added a link to Harvest since it's Harvest that 
handle errors now.
=> doc: Let's say it's KonnectorLibs that handle errors

OUTSIDE_DOCS
Fix cozy-app-publish repo URL from obsolete repo to subfolder of cozy-libs repo
=> docs: Fix cozy-app-publish source repo

mkdocs.yml.tpl
We prefer to redirect the user to our organization page with all our repos instead of just the doc's
repo.
=> feat: Link to orga not doc repo

src/howTos/dev/services.md
> The exit status of a pipeline is the exit status of the last command in the pipeline, unless the pipefail option is enabled (see The Set Builtin). If pipefail is enabled, the pipeline's return status is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands exit successfully.
Since tee exits 0, even if the service was failing, the result was 0.
=> docs: Update services.md

src/howTos/dev/run-connectors-on-local-cozy-stack.md
Explain how to avoid the re launch of errored konnectors on local stack
=> docs: Add option to avoid relaunch of errored konnectors

src/tutorials/app.md
The command may fails due to `yarn` cache error. When this happens, the fastest fix is to clear yarn cache, so lets add this to the documentation
=> docs: Add trouble shouting for `yarn create cozy-app` cache error

src/tutorials/selfhosting/administration/index.md, src/tutorials/selfhosting/administration/mail.md
This pull request adds documentation on how to configure cozy-stack for sending mail on selfhosting environments
=> docs: Document mail configuration for selfhosting

requirements.txt
Some dependencies cannot be installed with Python 3.12 and others make
use of old Python features which are not available anymore and prevent
us from building the project. This PR sets to upgrade those dependencies
to make building the project with Python 3.12 possible.
=> tech: Allow building with Python 3.12

.github/workflows/build-and-deploy.yml
With workflow_dispatch, we can now deploy manually the documentation
With the schedule, we'll deploy every day the documentation. 
Since end of February, the documentation was not published automatically anymore.
=> chore: Add Manual workflow & cron
